vim.api.nvim_set_var('netrw_liststyle', '3')
vim.api.nvim_set_var('netrw_winsize', '20')
vim.api.nvim_set_var('netrw_preview', '1')

vim.cmd(string.format('set %s', 'nocompatible'))
vim.cmd(string.format('set %s', 'path+=/home/jkarng/Project/**'))
vim.cmd(string.format('set %s', 'path+=**'))
vim.cmd(string.format('set %s', 'wildignore+=*/build/**'))
vim.cmd(string.format('set %s', 'wildignore+=*/.cache/**'))
vim.cmd(string.format('set %s', 'wildignore+=*/.git/**'))
vim.cmd(string.format('set %s', 'wildignore+=*/cmake/**'))
vim.cmd(string.format('set %s', 'wildignore+=*/cmake-scripts/**'))
vim.cmd(string.format('set %s', 'wildmenu'))

vim.api.nvim_set_keymap('n', '<leader>nl', [[:Lexplore<cr>]], {noremap=true, silent=true})
