#set -o vi
export MANPAGER="less -R --use-color -Dd+r -Du+b"

/usr/bin/setxkbmap -option "caps:escape"
#setxkbmap -layout us,apl -variant \
#  ,dyalog -option grp:shift_caps_toggle\
#  kr -option korean:ralt_hangul korean:rctrl_hanja

# setxkbmap -layout us,apl,kr -variant ,dyalog -option grp:switch -option lv3:rwin_switch
# refer /usr/share/X11/xkb/rules/evdev.lst
#/usr/bin/setxkbmap -option "caps:ctrl_modifier"

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

#[ -f ~/.fzf.bash ] && source ~/.fzf.bash
#source /usr/share/nvm/init-nvm.sh

ph=~/Project
#alias cda="cd $ph/ASM_Programming"
alias cda="cd $ph/modern_x86_64_assembly"
alias cdd="cd $ph/dots"
alias cdt="cd $ph/terms"
alias cdm="cd $ph/dic/mp3"
alias cdn="cd $ph/nasm_game"
alias cdv="cd $HOME/.config/nvim"

alias cdp="cd $ph"
alias cdc="cd $ph/cxx"

TEXMFDIST=/usr/share/texmf-dist
alias tlmgr='${TEXMFDIST}/scripts/texlive/tlmgr.pl --usermode'
alias vi='nvim'
alias vim='nvim'

# yarn config set prefix ~/.yarn-global
#export PATH="$PATH:`yarn global bin`"

#export LS_COLORS="$(vivid generate molokai)"

PATH="/home/jkarng/perl5/bin${PATH:+:${PATH}}"
PERL5LIB="/home/jkarng/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"
export PERL5LIB
PERL_LOCAL_LIB_ROOT="/home/jkarng/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"
export PERL_LOCAL_LIB_ROOT
PERL_MB_OPT="--install_base \"/home/jkarng/perl5\""
export PERL_MB_OPT
PERL_MM_OPT="INSTALL_BASE=/home/jkarng/perl5"
export PERL_MM_OPT

export XDG_RUNTIME_DIR=/run/user/$(id -u)
PATH="$HOME/.ghcup/bin:$PATH"
PATH="$HOME/.local/bin:$PATH"

PATH="$PATH:$HOME/.local/share/gem/ruby/3.0.0/bin"
PATH="$PATH:$HOME/.emacs.d/bin"
PATH="$PATH:$HOME/bin"

export PATH
#pyenv
#export PYENV_ROOT="$HOME/.pyenv"
#export PATH="$PYENV_ROOT/bin:$PATH"
#eval "$(pyenv init --path)"
