vim.api.nvim_set_var('netrw_liststyle', '3')
vim.api.nvim_set_var('netrw_winsize', '20')
vim.api.nvim_set_var('netrw_preview', '1')

vim.cmd(string.format('set %s', 'nocompatible'))
vim.cmd(string.format('set %s', 'path+=/home/jkarng/Project/dots/**'))
vim.cmd(string.format('set %s', 'path+=/home/jkarng/Project/nasm_game/**'))
vim.cmd(string.format('set %s', 'path+=/home/jkarng/Project/term/**'))
vim.cmd(string.format('set %s', 'path+=/home/jkarng/Project/cxx/**'))
vim.cmd(string.format('set %s', 'path+=/home/jkarng/Project/modern_x86_64_assembly/**'))
vim.cmd(string.format('set %s', 'path+=/usr/include/**'))
vim.cmd(string.format('set %s', 'wildignore+=*/build/**'))
vim.cmd(string.format('set %s', 'wildignore+=*/.cache/**'))
vim.cmd(string.format('set %s', 'wildignore+=*/.git/**'))
vim.cmd(string.format('set %s', 'wildignore+=*/cmake/**'))
vim.cmd(string.format('set %s', 'wildignore+=*/mov/**'))
vim.cmd(string.format('set %s', 'wildignore+=*/pdf/mov**'))
vim.cmd(string.format('set %s', 'wildignore+=*/cmake-scripts/**'))
vim.cmd(string.format('set %s', 'wildmenu'))

vim.api.nvim_set_keymap('n', '<leader>nl', [[:Lexplore<cr>]], {noremap=true, silent=true})
