#!/bin/bash
daum="https://dic.daum.net"
daum_sch="${daum}/search.do?q"
dic_all='&dic=all'
daum_id="${daum}/word/view.do?wordid" #=ekw000146827
daum_tts="https://tts-dic.daum.net/read?lang=en&txt" #=

audio_dir=~/Project/dic/mp3
all_audios=${audio_dir}/*.mp3

function saveMp3(){
  M_SFILE=${audio_dir}/${WD}${num}.mp3
  let num++
  curl -o "${M_SFILE}" "${1}" > /dev/null 2>&1

  mpv $M_SFILE > /dev/null 2>&1
  echo $1
}

function setVAR(){
  W1=${1%%.*}
  W2=${W1##*/}

  W3=${W2%%_*}
  W4=${W3%%-*}

  EE=$(sed -En '1p' <<< $(checkNgetSpell $W4))
  EK=$(sed -En '$p' <<< $(checkNgetSpell $W4))
  ER=$(sed -En '/^[^\/a-zA-Z]+/p' <<< $(checkNgetSpell $W4))

  WD=$(sed -En 's/^[^a-zA-Z]*([a-zA-Z]+)/\1/p' <<< ${ER})
  WD=${WD:-${W4}}

  M_SFILE=${audio_dir}/${WD}
  [[ -f ${M_SFILE}_0.mp3 ]] && M_NEW="" || M_NEW='OK'
}


function trimVoice(){
  sed -E -e '/\+/{s/.*_(.+)\.mp3$/\1/}'\
    -e '/\+/!{s/.*\/([^_]+)_.*/\1/}' <<< $1
}

function urlEncoding(){
  sed -E -e '/%27|&#039/{s//'"'"'/g}'\
         -e '/%3A/{s//:/g}'\
         -e '/%2C/{s//,/g}'\
         -e 's/\+/ /g' <<< $1
}

function checkNgetSpell(){
  # <a href="/word/view.do?wordid=eew000034775"
    sed -En -e ':X N; /link_speller/{s/>([^<]+)<|./\1/g;H;n;n;n;n;n}'\
            -e '/do\?wordid=ek/{/eku/!{s/[^"]*"([^"]+).*/\1/;H;n}}'\
            -e '/do\?wordid=ee/{s/[^"]*"([^"]+).*/\1/;TX;G;p;q}' <<< $( curl -s -A 'Mozilla/4.0' "${daum_sch}=$1" )
}

function showEDic(){
    curl -s -A 'Mozilla/4.0' "${daum}${EE}"\
      |sed -En -e '/txt_mean/{s/>([^<]+)<|./\1/g;{s/.*/\t&/;bX}}'\
            -e 'b'\
            -e ':X p'

}

function dic_All(){

            #-e '/data-audio data-url="http/{s/data-url="([^"]+)|>([^<]+)<|./\1\2/g;{s/(.*[^,])?(\s+)?(http.*)/echo "\1";curl -o '${FNAME}' \3 > \/dev\/null 2>\&1;mpv '"${FNAME}"' > \/dev\/null 2>\&1;echo '"${FNAME}"'/e;bY}}'\
    FNAME="~\/Project\/dic\/mp3\/${1}.mp3"
    
    clear
    echo "===== "${WD} ${M_NEW/OK/**}" ====="
    curl -s -A 'Mozilla/4.0' "${daum_sch}=${1}"\
      |sed -En -e '/tit_speller/{s/>([^<]+)<|./\1/g;bX}'\
      -e '/data-audio data-url="http/{s/data-url="([^"]+)|>([^<]+)<|./\1\2/g;bY}'\
            -e '/"tit_word"/{s/.*>\s?([^<]+)<.*/\n\t<<< \1 >>>/;bX}'\
            -e '/"txt_emph1"/{s/>([^<]+)<|./\1/g;s/.*/\n  << & >>\n/;bX}'\
            -e '/txt_search"/{/num_search"/!{s/>([^<]+)<|./\1/g;s/.*/    &/;bX}}'\
            -e '/num_search/{/txt_search"/{s/>([^<]+)<|./\1/g;s/.*/\t&/;bX}}'\
            -e 'b'\
            -e ':Y s/^(.*)\s+(.*)/\2\1/p;q' \
            -e ':X p; e sleep 1'

    echo "================ END ==================="
}

dic_All $1
exit

function showKDic(){
    #clear
    echo "===== "${ER:-${WD}} ${M_NEW/OK/**/}:${EE}:${EK}" ====="
    curl -s -A 'Mozilla/4.0' "${daum}${EK}"\
      |sed -En -e '/num_mean/{s/>([^<]+)<|./\1/g;s/[0-9]\.[^0-9]+/\n&/g;s/\.\s+/. /g;bX}'\
            -e '/txt_pronounce/{s/>([^<]+)|./\1/g;bX}'\
            -e '/data-audio data-url="http/{s/data-url="([^"]+)"|./\1/g;bX}'\
            -e '/inner_tit/{s/.*>([^<]+)<.*/\n<<< \1 >>>/;bX}'\
            -e '/tit_sort/{s/.*>([^>]+)<.*/\n\t<< \1 >>/g;bX}'\
            -e '/txt_sort/{s/.*>([^<]+)<.*>([^<]+)<.*/    \1 => \2/g;bX}'\
            -e '/"tit_word"/{s/.*>\s?([^<]+)<.*/\n\t<< \1 >>\n/;bX}'\
            -e '/"txt_emph1"/{s/>([^<]+)<|./\1/g;s/.*/ &/;bX}'\
            -e '/"mean_info"/{s/>([^<]+)<|./\1/g;s/.*/  &\n/;bX}'\
            -e 'b'\
            -e ':X p'
    echo "<< ${WD} >>"
    showEDic

    echo "================ END ==================="
}

function playdic(){

            awk -v SFILE=${M_SFILE} -v NEW=${M_NEW} 'BEGIN{FNAME; I;}

            {if($0 ~ /http/) {
                    if(/&format/){\
                      FNAME = gensub(/.*en&*txt=([^&.]+).*/,SFILE"_\\1.mp3","1")
                    }else {
                      FNAME = SFILE"_"(I++)".mp3"
                    }
                    
                      if(NEW=="OK"){
                        cmd_curl="xargs -I{} curl -o "FNAME" {} > /dev/null 2>&1" 
                        print $0 | cmd_curl
                        close(cmd_curl)
                      }
                      cmd_mpv="mpv "FNAME" > /dev/null 2>&1"
                      print $0 | cmd_mpv 
                      close (cmd_mpv)
                }else  print $0

              print "sleep 1" | "/bin/bash"
              close("/bin/bash")
            }' <<< $1
}

function playLocal(){
  [[ ${1} != '' ]] && v1=${1/%/_0} || v1="*_0"
  for i in ${audio_dir}/${v1}.mp3
    do 
        setVAR ${i}
  echo Local-W4:$W4
  echo M_SFILE:$M_SFILE
  echo M_NEW:$M_NEW
        dic_All ${W4}
    done
}


function mainDic(){
  setVAR $1
  echo W4:$W4
  echo M_SFILE:$M_SFILE
  echo M_NEW:$M_NEW
    playdic "$( dic_All $W4 )" ${M_SFILE} ${M_NEW}
}

[[ -n $1 ]] && (mainDic $1; exit;) || (playLocal; exit;)
