#!/bin/bash

daum="https://dic.daum.net/search.do?q"
dic_dir="~/Project/dic/mp3"
all_audios="${dic_dir}/*.mp3"

      curl -s -A 'Mozilla/4.0' "${daum}=${1}" |\
      sed -E 's/data-audio data-url="(http[^"]+)"|./\1/g' |\
      sed -En '/^$/!p' 
  
