#!/bin/bash

daum="https://dic.daum.net/search.do?q"
mp3_dir="/Project/dic/mp3"

function getWd(){
  local fW=${1%%.*}
  local fW1=${W##*/}
  local fW2=${W1%%-*}
  curl -s -A 'Mozilla/4.0' "${daum}=${fW2}"|\
  awk /wordid/ |\
  awk 'NR==1{print $0}' |\
  sed -E 's/.*>(\w+).*/\1/'
}

W=${1%%.*}
W1=${W##*/}
W2=${W1%%-*}

wd=$(getWd $1)
if [[ $wd != $W2 ]]; then clear; echo "=== Did u mean ${wd} instead of ${W2}===";sleep 1; else echo $W2; fi

wd_audio=${mp3_dir}/${wd}*.mp3
all_audios=${mp3_dir}/*.mp3

function getWid(){
  local fwd=$(getWd $1)
  curl -s -A 'Mozilla/4.0' "${daum}=${fwd}"|\
    awk /wordid/ | \
    awk 'NR==1{print $0}' | \
    awk -F'=' '{print $3}' | \
    sed -E 's/(.*)\" class$/\1/'
}

function printDic(){
  local fwd=$(getWd $1)
    echo "#######- ${fwd} -#######" && \
    curl -s -A 'Mozilla/4.0' "${daum}=${fwd}" |\
    sed -E 's/[^>]+|([^<]+)/\1/g' |\
    sed -En '/완료/,/영영사전 더보기/p' |\
    sed -E '/^>+$/d' |\
    sed -E 's/<|>//g' |\
    sed -E '/^듣기$|^영영사전|^영어사전/d' |\
    awk '!x[$0]++' |\
    sed -E 's/(\.)(\S)/\1 \2/' |\
    sed -E 's/^[0-9]/\t&/'
    echo "================ END ==================="
}

function playall(){
  for i in ${all_audios}; do printDic ${i}; mpv ${i} > /dev/null 2>&1; sleep 1; mpv ${i} > /dev/null 2>&1; sleep 1; mpv ${i} > /dev/null 2>&1; sleep 1; clear; done
}

#####################
function getMp3(){
  echo start
  curl -s -A 'Mozilla/4.0' "${daum}=${wd}"|\
  sed -En 's/.*data-url="([^"]+)".*/\1/p' |\
  sed -En '1p' |\
  xargs -I{} curl -o ./${wd}.mp3 {}
}

getMp3
