#!/bin/bash
#daum_tts="http://tts-dic.daum.net/read?lang=${2:-en}&txt=Look+at+the+response+to+the+tsunami+--+it%27s+inspiring.&format=mpeg

function pre_encode(){
  sed -E -e 's/\s+/ /g' \
         -e 's/^\s+//' \
         -e 's/ /+/g' <<< "$1"
}

function url_encode(){
    local str=$( pre_encode "${1}" )
    local strlen=${#str}
    local encoded=""
    local pos c o

    for (( pos=0 ; pos<strlen ; pos++ )) 
    do
      c=${str:$pos:1}
      case "$c" in
        [+-_,~a-zA-Z0-9] ) 
          o="${c}" 
          ;;

        * )               
          o=$( xxd -p <<< "${c}" | sed -E ':X s/^([^%]*)([^%]{2})/\1%\2/;tX;s/(.*)...$/\1/' )
          ;;
      esac
      encoded+="${o}"
    done
    echo $"${encoded}"
}

audio_dir="${HOME}/Project/dic/mp3"
filename="${audio_dir}/${1}.mp3"

daum_tts="http://tts-dic.daum.net/read"
txt="$( url_encode "$1" )"
lang="${2:-en}"
format="mpeg"

url="${daum_tts}?lang=${lang}&txt=${txt}&format=${format}"
mpv ${url} > /dev/null 2>&1

#curl -G -s\
#  -o "${filename}" \
#  "${url}" \
#&& mpv "${filename}" > /dev/null 2>&1

# curl -G -s\
#   -o "${filename}" \
#   --data-urlencode "lang=${lang}" \
#   --data-urlencode "txt=${txt}" \
#   --data-urlencode "format=${format}" \
#   "${daum_tts}" 
# && mpv ${filename} > /dev/null 2>&1

